{
 "title": "OpenStack Performance Management Dashboard",
 "description": "Basic Performance Management Dashboard for OpenStack System",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(job)" },
   { "name": "host", "label": "Host", "query": "up" },
   {
    "name": "VM",
    "label": "OpenStack Instance",
    "query": "collectd_virt_percent{exported_host_fqdn=~\"$host\"}"
   },
   {
    "name": "ContainerOnHost",
    "label": "Container Name",
    "query": "container_last_seen{exported_host_fqdn=~\"$host\"}"
   }
  ]
 },
 "panels": [
  { "title": "Host Summary Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total CPU",
   "type": "stat",
   "description": "The total numbers for vCPU",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "vCPU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(collectd_cpu_percent{exported_host_fqdn=~\"${host}\",type=\"idle\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "collectd_table_memory{exported_host_fqdn=~\"${host}\",type=\"MemTotal\"}"
    }
   ]
  },
  {
   "title": "Host CPU / Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "avg_cpu (Idle)",
     "type": "timeseries",
     "description": "take average from all CPUs idle value",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(collectd_cpu_percent{exported_host_fqdn=~\"$host\",type=\"idle\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "CPU Percent / Per CPU",
     "type": "timeseries",
     "description": "Check every single CPU idle ",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "collectd_cpu_percent{exported_host_fqdn=~\"$host\",type=\"idle\"}",
       "legendFormat": " {{ cpu }}"
      }
     ]
    },
    {
     "title": "System Load Average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "collectd_load_shortterm{exported_instance=~\"$host\"}",
       "legendFormat": "shortterm"
      },
      {
       "expr": "collectd_load_midterm{exported_instance=~\"$host\"}",
       "legendFormat": "midterm"
      },
      {
       "expr": "collectd_load_longterm{exported_instance=~\"$host\"}",
       "legendFormat": "longterm"
      }
     ]
    },
    {
     "title": "MemInfo",
     "type": "timeseries",
     "description": "MemAvailable from /proc/meminfo",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "collectd_table_memory{exported_host_fqdn=~\"$host\",type=~\"MemFree\"}",
       "legendFormat": "MemFree"
      },
      {
       "expr": "collectd_table_memory{exported_host_fqdn=~\"$host\",type=~\"MemAvailable\"}",
       "legendFormat": "MemAvailable"
      }
     ]
    },
    {
     "title": "NUMA Metrics",
     "type": "timeseries",
     "description": "collectd_numa_vmpage_action_total",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "rate(collectd_numa_vmpage_action_total{exported_host_fqdn=~\"${host}\",numa=\"node0\"}[1m])",
       "legendFormat": "{{ type }} - node0"
      },
      {
       "expr": "rate(collectd_numa_vmpage_action_total{exported_host_fqdn=~\"${host}\",numa=\"node1\"}[1m])",
       "legendFormat": "{{ type }} - node1"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Use%",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "collectd_df_percent_bytes{job=\"collectd\",exported_host_fqdn=~\"$host\",df!=\"tmpfs\",df!=\"devtmpfs\",df!=\"overlay\",type=\"used\"}",
       "legendFormat": "{{df}}"
      }
     ]
    },
    {
     "title": "Disk Total Traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(collectd_disk_disk_octets_read_total{job=\"collectd\",exported_host_fqdn=~\"$host\",disk!~\"scini..*\",disk!~\"loop0\",disk!~\"dm..*\"}[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(rate(collectd_disk_disk_octets_write_total{job=\"collectd\",exported_host_fqdn=~\"$host\",disk!~\"scini..*\",disk!~\"loop0\",disk!~\"dm..*\"}[5m]))",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Disk Operations Total",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(collectd_disk_disk_ops_read_total{job=\"collectd\",exported_host_fqdn=~\"$host\",disk!~\"loop0\"}[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(rate(collectd_disk_disk_ops_write_total{job=\"collectd\",exported_host_fqdn=~\"$host\",disk!~\"scini..*\",disk!~\"loop0\",disk!~\"dm..*\"}[5m]))",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Read Operation By Disk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(collectd_disk_disk_octets_read_total{job=\"collectd\",exported_host_fqdn=~\"$host\"}[5m])",
       "legendFormat": "{{ disk }}"
      }
     ]
    },
    {
     "title": "Write Operation By Disk",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(collectd_disk_disk_octets_write_total{job=\"collectd\",exported_host_fqdn=~\"$host\"}[5m])",
       "legendFormat": "{{ disk }}"
      }
     ]
    },
    {
     "title": "Disk Pending Operations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(collectd_disk_pending_operations{job=\"collectd\",exported_host_fqdn=~\"$host\"})",
       "legendFormat": "pending operation"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Network NetStats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface Packets Total",
     "type": "timeseries",
     "description": "collectd_interface_if_packets_rx_total\ncollectd_interface_if_packets_tx_total",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(collectd_interface_if_packets_rx_total{job=\"collectd\",exported_host_fqdn=~\"$host\",interface!~\"lo|trk.*\"}[5m])",
       "legendFormat": "Rx {{interface}}"
      },
      {
       "expr": "irate(collectd_interface_if_packets_tx_total{job=\"collectd\",exported_host_fqdn=~\"$host\",interface!~\"lo|trk.*\"}[5m])",
       "legendFormat": "Tx {{interface}}"
      }
     ]
    },
    {
     "title": "Interface Packets Drop",
     "type": "timeseries",
     "description": "collectd_interface_if_dropped_rx_total\ncollectd_interface_if_dropped_tx_total",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(collectd_interface_if_dropped_rx_total{job=\"collectd\",exported_host_fqdn=~\"$host\",interface!~\"lo|tap.*|trk.*\"}[5m])",
       "legendFormat": "Rx {{interface}}"
      },
      {
       "expr": "irate(collectd_interface_if_dropped_tx_total{job=\"collectd\",exported_host_fqdn=~\"$host\",interface!~\"lo|tap.*|trk.*\"}[5m])",
       "legendFormat": "Tx {{interface}}"
      }
     ]
    },
    {
     "title": "Interface Packets Error",
     "type": "timeseries",
     "description": "collectd_interface_if_errors_rx_total\ncollectd_interface_if_errors_tx_total",
     "gridPos": { "h": 7, "w": 23, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(collectd_interface_if_errors_rx_total{job=\"collectd\",exported_host_fqdn=~\"$host\",interface!~\"lo|trk.*\"}[5m])",
       "legendFormat": "rx {{interface}}"
      },
      {
       "expr": "irate(collectd_interface_if_errors_tx_total{job=\"collectd\",exported_host_fqdn=~\"$host\",interface!~\"lo|trk.*\"}[5m])",
       "legendFormat": "tx {{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Container Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU Utilization",
     "type": "timeseries",
     "description": "container_cpu_util",
     "gridPos": { "h": 8, "w": 22, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "container_cpu_util{exported_host_fqdn=~\"$host\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Container Memory Usage",
     "type": "timeseries",
     "description": "container_memory_usage_bytes",
     "gridPos": { "h": 6, "w": 22, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{job=\"cadvisor\",exported_host_fqdn=~\"$host\",name!~\"\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Process Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "host",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU & Memory Usage by CSS",
     "type": "timeseries",
     "description": "The metric indicates the reachability status of an upstream NTP server from the LCM server. It reports whether the upstream server is reachable or not. The metric provides a binary value of either 0 (zero) or 1 (one). A value of 0 (zero) represents that the upstream NTP server is not reachable from the LCM server and a value of 1 (one) represents that the upstream server is reachable.\nCheck it from Infra nodes only",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "collectd_utilization_gauge{exported_host_fqdn=~\"${host}\"}",
       "legendFormat": "{{ utilization }}"
      }
     ]
    },
    {
     "title": "NTP Upstream Server Reachability",
     "type": "timeseries",
     "description": "The metric indicates the reachability status of an upstream NTP server from the LCM server. It reports whether the upstream server is reachable or not. The metric provides a binary value of either 0 (zero) or 1 (one). A value of 0 (zero) represents that the upstream NTP server is not reachable from the LCM server and a value of 1 (one) represents that the upstream server is reachable.\nCheck it from Infra nodes only",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "targets": [
      {
       "expr": "collectd_ntp_upstream_server_reach_status_gauge{exported_host_fqdn=~\"${host}\"}",
       "legendFormat": "{{ ntp_upstream_server_reach_status }}"
      }
     ]
    }
   ]
  },
  {
   "title": "VM Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total VM Interface Traffic by Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(collectd_virt_if_packets_rx_total{job=\"collectd\",exported_instance=~\"$VM\"}[5m])",
       "legendFormat": "rx  {{ exported_instance }} - {{ virt }}"
      },
      {
       "expr": "irate(collectd_virt_if_packets_tx_total{job=\"collectd\",exported_instance=~\"$VM\"}[5m])",
       "legendFormat": "tx  {{ exported_instance }} - {{ virt }}"
      }
     ]
    },
    {
     "title": "Single VM Interface Traffic by Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(collectd_virt_if_packets_rx_total{job=\"collectd\",exported_host_fqdn=~\"$host\",exported_instance=~\"$VM\"}[5m])",
       "legendFormat": "rx  {{virt}}"
      },
      {
       "expr": "irate(collectd_virt_if_packets_tx_total{job=\"collectd\",exported_host_fqdn=~\"$host\",exported_instance=~\"$VM\"}[5m])",
       "legendFormat": "tx  {{virt}}"
      }
     ]
    },
    {
     "title": "Single VM Interface Packet Drop",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(collectd_virt_if_dropped_rx_total{job=\"collectd\",exported_host_fqdn=~\"$host\",exported_instance=~\"$VM\"}[5m])",
       "legendFormat": "rx_drop  {{virt}}"
      },
      {
       "expr": "irate(collectd_virt_if_dropped_tx_total{job=\"collectd\",exported_host_fqdn=~\"$host\",exported_instance=~\"$VM\"}[5m])",
       "legendFormat": "tx_drop  {{virt}}"
      }
     ]
    },
    {
     "title": "VM Disk Ops Total",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(collectd_virt_disk_ops_read_total{job=\"collectd\",exported_host_fqdn=~\"$host\",exported_instance=~\"$VM\",virt!~\"hdd\"}[5m])",
       "legendFormat": "Read {{virt}}"
      },
      {
       "expr": "irate(collectd_virt_disk_ops_write_total{job=\"collectd\",exported_host_fqdn=~\"$host\",exported_instance=~\"$VM\",virt!~\"hdd\"}[5m])",
       "legendFormat": "write {{virt}}"
      }
     ]
    },
    {
     "title": "Single VM Disk Usage Time (To Be Checked)",
     "type": "timeseries",
     "description": "collectd_virt_disk_time_read_total\ncollectd_virt_disk_time_write_total",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "µs" } }
    }
   ]
  },
  {
   "title": "OVS Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface Packets Total",
     "type": "timeseries",
     "description": "collectd_ovs_stats_if_packets_rx_total\ncollectd_ovs_stats_if_packets_tx_total",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(collectd_ovs_stats_if_packets_rx_total{exported_host_fqdn=~\"$host\",ovs_stats=~\"br-int.*|tbr-.*|br_prv-.*\"}[5m])",
       "legendFormat": "Rx {{ ovs_stats }}"
      },
      {
       "expr": "irate(collectd_ovs_stats_if_packets_tx_total{exported_host_fqdn=~\"$host\",ovs_stats=~\"br-int.*|tbr-.*|br_prv-.*\"}[5m])",
       "legendFormat": "Tx {{ ovs_stats }}"
      }
     ]
    },
    {
     "title": "Interface Packets Dropped Total",
     "type": "timeseries",
     "description": "collectd_ovs_stats_if_dropped_rx_total & \ncollectd_ovs_stats_if_dropped_tx_total",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(collectd_ovs_stats_if_dropped_rx_total{exported_host_fqdn=~\"$host\",ovs_stats=~\"br-int.*|tbr-.*|br_prv-.*\"}[5m])",
       "legendFormat": "Rx {{ ovs_stats }}"
      },
      {
       "expr": "irate(collectd_ovs_stats_if_dropped_tx_total{exported_host_fqdn=~\"$host\",ovs_stats=~\"br-int.*|tbr-.*|br_prv-.*\"}[5m])",
       "legendFormat": "Tx {{ ovs_stats }}"
      }
     ]
    },
    {
     "title": "Interface Packets Error Total",
     "type": "timeseries",
     "description": "collectd_ovs_stats_if_errors_rx_total& \ncollectd_ovs_stats_if_errors_tx_total",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(collectd_ovs_stats_if_errors_rx_total{exported_host_fqdn=~\"$host\",ovs_stats=~\"br-int.*|tbr-.*|br_prv-.*\"}[1m])",
       "legendFormat": "Rx {{ ovs_stats }}"
      },
      {
       "expr": "irate(collectd_ovs_stats_if_errors_tx_total{exported_host_fqdn=~\"$host\",ovs_stats=~\"br-int.*|tbr-.*|br_prv-.*\"}[1m])",
       "legendFormat": "Tx {{ ovs_stats }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Mysql For Openstack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "MYSQL Handler For Nova",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(collectd_mysql_mysql_handler_total{exported_host_fqdn=~\"$host\",mysql=~\"nova|nova_api\"}[5m])",
       "legendFormat": "{{mysql}} / {{type}}"
      }
     ]
    },
    {
     "title": "MYSQL Handler For Neutron",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(collectd_mysql_mysql_handler_total{exported_host_fqdn=~\"$host\",mysql=~\"neutron\"}[5m])",
       "legendFormat": "{{mysql}} / {{type}}"
      }
     ]
    },
    {
     "title": "MYSQL Handler For Watchmen",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(collectd_mysql_mysql_handler_total{mysql=~\"watchmen\"}[5m])",
       "legendFormat": "{{exported_host_fqdn}} / {{mysql}} / {{type}}"
      }
     ]
    },
    {
     "title": "MYSQL Commands For Nova",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(collectd_mysql_mysql_commands_total{exported_host_fqdn=~\"$host\",mysql=~\"nova|nova_api\"}[5m])",
       "legendFormat": "{{mysql}} / {{type}}"
      }
     ]
    },
    {
     "title": "MYSQL Commands For Neutron",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(collectd_mysql_mysql_commands_total{exported_host_fqdn=~\"$host\",mysql=~\"neutron\"}[5m])",
       "legendFormat": "{{mysql}} / {{type}}"
      }
     ]
    },
    {
     "title": "MYSQL Commands For Watchmen",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(collectd_mysql_mysql_commands_total{mysql=~\"watchmen\"}[5m])",
       "legendFormat": "{{exported_host_fqdn}} / {{mysql}} / {{type}}"
      }
     ]
    },
    {
     "title": "MYSQL Traffic For Nova",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(collectd_mysql_mysql_octets_rx_total{exported_host_fqdn=~\"$host\",mysql=~\"nova|nova_api\"}[5m])",
       "legendFormat": "Rx - {{mysql}}"
      },
      {
       "expr": "irate(collectd_mysql_mysql_octets_tx_total{exported_host_fqdn=~\"$host\",mysql=~\"nova|nova_api\"}[5m])",
       "legendFormat": "Tx - {{mysql}}"
      }
     ]
    },
    {
     "title": "MYSQL Traffic For Neutron",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(collectd_mysql_mysql_octets_rx_total{exported_host_fqdn=~\"$host\",mysql=~\"neutron\"}[5m])",
       "legendFormat": "Rx - {{mysql}}"
      },
      {
       "expr": "irate(collectd_mysql_mysql_octets_tx_total{exported_host_fqdn=~\"$host\",mysql=~\"neutron\"}[5m])",
       "legendFormat": "Tx - {{mysql}}"
      }
     ]
    },
    {
     "title": "MYSQL Traffic For Watchmen",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(collectd_mysql_mysql_octets_rx_total{mysql=~\"watchmen\"}[5m])",
       "legendFormat": "Rx {{exported_host_fqdn}} / {{mysql}}"
      },
      {
       "expr": "irate(collectd_mysql_mysql_octets_tx_total{mysql=~\"watchmen\"}[5m])",
       "legendFormat": "Tx {{exported_host_fqdn}} / {{mysql}}"
      }
     ]
    },
    {
     "title": "MYSQL Total Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 22, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "collectd_mysql_total_threads_total{}",
       "legendFormat": "{{exported_host_fqdn}} - {{mysql}}"
      }
     ]
    }
   ]
  }
 ]
}